# Generated by Django 4.1.6 on 2023-02-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0002_listing_latitude_listing_longitude"),
    ]

    operations = [
        migrations.RemoveField(model_name="listing", name="latitude",),
        migrations.RemoveField(model_name="listing", name="longitude",),
        migrations.AddField(
            model_name="listing",
            name="picture1",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
