# Generated by Django 4.1.6 on 2023-02-10 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "listings",
            "0005_listing_picture2_listing_picture3_listing_picture4_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(model_name="listing", name="latitude",),
        migrations.RemoveField(model_name="listing", name="longitude",),
    ]
